<?php require 'config.php'; require 'header.php'; $uid=$_SESSION['user_id'];
if(isset($_POST['add'])){ $s=$conn->prepare("INSERT INTO appointments(user_id,member_id,doctor_name,appointment_date,appointment_time,place,notes) VALUES(?,?,?,?,?,?,?)"); $s->bind_param("iisssss",$uid,$_POST['member_id'],$_POST['doctor_name'],$_POST['appointment_date'],$_POST['appointment_time'],$_POST['place'],$_POST['notes']); $s->execute(); header("Location: appointments.php"); exit; }
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; $conn->query("DELETE FROM appointments WHERE id=$id AND user_id=$uid"); header("Location: appointments.php"); exit; }
$members=$conn->query("SELECT id,name FROM family_members WHERE user_id=$uid ORDER BY name");
$list=$conn->query("SELECT a.*,f.name member_name FROM appointments a JOIN family_members f ON f.id=a.member_id WHERE a.user_id=$uid ORDER BY a.appointment_date,a.appointment_time");
?>
<div class="container"><h2>Doctor Appointments</h2><div class="form-card"><h3>Add Appointment</h3>
<form method="post"><label>Family Member</label><select name="member_id" required><?php while($m=$members->fetch_assoc()): ?><option value="<?=$m['id']?>"><?=htmlspecialchars($m['name'])?></option><?php endwhile; ?></select>
<label>Doctor / Clinic Name</label><input name="doctor_name" required><label>Date</label><input type="date" name="appointment_date" required><label>Time</label><input type="time" name="appointment_time" required><label>Place</label><input name="place"><label>Notes</label><input name="notes"><button class="btn" name="add">Save Appointment</button></form></div>
<div class="card"><table><tr><th>Member</th><th>Doctor/Clinic</th><th>Date</th><th>Time</th><th>Place</th><th>Action</th></tr><?php while($r=$list->fetch_assoc()): ?><tr><td><?=htmlspecialchars($r['member_name'])?></td><td><?=htmlspecialchars($r['doctor_name'])?></td><td><?=htmlspecialchars($r['appointment_date'])?></td><td><?=htmlspecialchars($r['appointment_time'])?></td><td><?=htmlspecialchars($r['place'])?></td><td><a class="btn danger small" href="?delete=<?=$r['id']?>" onclick="return confirm('Delete appointment?')">Delete</a></td></tr><?php endwhile; ?></table></div></div>
