<?php require 'config.php'; require 'header.php'; $uid=$_SESSION['user_id'];
if(isset($_POST['add'])){ $s=$conn->prepare("INSERT INTO care_tasks(user_id,member_id,task_name,task_date,task_time) VALUES(?,?,?,?,?)"); $s->bind_param("iisss",$uid,$_POST['member_id'],$_POST['task_name'],$_POST['task_date'],$_POST['task_time']); $s->execute(); header("Location: care_tasks.php"); exit; }
if(isset($_GET['done'])){ $id=(int)$_GET['done']; $conn->query("UPDATE care_tasks SET status='Completed' WHERE id=$id AND user_id=$uid"); header("Location: care_tasks.php"); exit; }
if(isset($_GET['delete'])){ $id=(int)$_GET['delete']; $conn->query("DELETE FROM care_tasks WHERE id=$id AND user_id=$uid"); header("Location: care_tasks.php"); exit; }
$members=$conn->query("SELECT id,name FROM family_members WHERE user_id=$uid ORDER BY name");
$list=$conn->query("SELECT c.*,f.name member_name FROM care_tasks c JOIN family_members f ON f.id=c.member_id WHERE c.user_id=$uid ORDER BY c.task_date,c.task_time");
?>
<div class="container"><h2>Daily Care Tasks</h2><div class="form-card"><h3>Add Task</h3><form method="post">
<label>Family Member</label><select name="member_id" required><?php while($m=$members->fetch_assoc()): ?><option value="<?=$m['id']?>"><?=htmlspecialchars($m['name'])?></option><?php endwhile; ?></select>
<label>Task</label><input name="task_name" placeholder="Example: personal reminder" required><label>Date</label><input type="date" name="task_date" value="<?=date('Y-m-d')?>" required><label>Time</label><input type="time" name="task_time"><button class="btn" name="add">Add Task</button></form></div>
<div class="card"><table><tr><th>Member</th><th>Task</th><th>Date</th><th>Time</th><th>Status</th><th>Action</th></tr><?php while($r=$list->fetch_assoc()): ?><tr><td><?=htmlspecialchars($r['member_name'])?></td><td><?=htmlspecialchars($r['task_name'])?></td><td><?=$r['task_date']?></td><td><?=$r['task_time']?></td><td><?=$r['status']?></td><td class="actions"><?php if($r['status']==='Pending'): ?><a class="btn success small" href="?done=<?=$r['id']?>">Complete</a><?php endif; ?><a class="btn danger small" href="?delete=<?=$r['id']?>">Delete</a></td></tr><?php endwhile; ?></table></div></div>
